### ISSUE TITLE
Option for v2 alongside v3.3

### ISSUE THREAD

**Issue by alfureu** [composerize/composerize#406]
I was wondering whether it would be an option to include a switch for generating docker-compose v2 next to the current v3.3. Few of us use Portainer, which still does not support v3 in its stack unfortunately...

**Comment by magicmark** [comment]
Sounds like a good feature!

Do you have an idea for what the UI / changes to the code might look like? Wanna take a stab at spearheading this?

**Comment by DOFfactory** [comment]
Hi @magicmark no idea how the conversion is happening between v2 and v3, have not found a documentation about it. This also means that I unfortunately cannot help you with the implementation. Regarding the UI solution, I though that a drop-down menu on the left could turn the default v3 docker-compose into a v2 and vice versa.

**Comment by magicmark** [comment]
@DOFfactory sounds good - lmk if you want to champion this effort :)

**Comment by sharevb** [comment]
Hi all, as far as I read on converting version: 2 to version: 3, there not so much options changed : https://docs.docker.com/compose/compose-file/compose-versioning/#upgrading

**Comment by sharevb** [comment]
-   `group_add`: sounds like is supported in last 3.x specs https://docs.docker.com/compose/compose-file/05-services/#group_add, so no difference
-   `volumes_from`: sounds like is supported in last 3.x specs https://docs.docker.com/compose/compose-file/05-services/#volumes_from
   
-   `cpu_shares`: sounds like is supported in last 3.x specs https://docs.docker.com/compose/compose-file/05-services/#cpu_shares
-   `cpu_quota`: sounds like is supported in last 3.x specs https://docs.docker.com/compose/compose-file/05-services/#cpu_quota
-   `cpuset`: sounds like is supported in last 3.x specs https://docs.docker.com/compose/compose-file/05-services/#cpuset
-   `memswap_limit`: sounds like is supported in last 3.x specs https://docs.docker.com/compose/compose-file/05-services/#memswap_limit

-   `mem_limit`: so for 2.x, it is at `service` level (not in `deploy` resources) but in 3.x it seems just ignored outside of swarm, same thing for all `deploy` section that maps to `service` level properties (https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu_count-cpu_percent-cpu_shares-cpu_period-cpu_quota-cpus-cpuset-domainname-hostname-ipc-mac_address-mem_limit-memswap_limit-mem_swappiness-mem_reservation-oom_kill_disable-oom_score_adj-privileged-read_only-shm_size-stdin_open-tty-user-working_dir) instead of `deploy` (https://docs.docker.com/compose/compose-file/deploy/#memory)
-   `pids_limit`: so for 2.x, it is at `service` level (not in `deploy` section) but in 3.x it seems just ignored outside of *swarm* (like all `deploy` section but not sure)
   
-   `extends`:  no `docker run` option related to this
-   `volume_driver`: no `docker run` option related to this
-   `link_local_ips`  in  `networks`: so for 2.x, just ignored/removed

So the main process to make a 2.x is to transform `deploy` section, and remove `link_local_ips`

**Comment by sharevb** [comment]
Will add an option to produce 2.x or 3.x ; and the abilty to merge with an existing docker compose file V1 or V2 (2.x or 3.X)

**Comment by sharevb** [comment]
There is now a Docker compose format version selector in composerize.com
