### ISSUE TITLE
The resource failed to load

### ISSUE THREAD

**Issue by wxyShine** [composerize/composerize#587]
![image](https://github.com/composerize/composerize/assets/42802152/7aaf3616-b999-4b7c-af3b-d0737aa80512)

demo page https://www.composerize.com/

**Comment by sharevb** [comment]
Hi,

Thanks for this issue. By the way:
- carbon.js is an ad system added by original author of this project. Will not remove myself. Failed to load because blocked by something like uBlock Origin
- count.js (goat counter) is a small "visit counter", privacy aware as far as I know, also failed to load because blocked by something like uBlock Origin
- did not reproduce loading failure of fontawesome.woff in Chrome

By the way, nothing to fix at the time being
